[package]
name = "ton-address"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = { version = "0.22.1" }
crc = { version = "3.2.1" }
thiserror = { version = "1.0.62" }
hex = { version = "0.4.3" }