name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Nightly toolchain for tests"
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rustfmt, clippy, rust-src, cargo-tarpaulin

      - name: "Check fmt"
        run: cargo fmt --check

      - name: "Run clippy"
        run: cargo clippy

      - name: "Build"
        run: cargo build --verbose

      - name: "Run tests & generate code coverage"
        run: cargo tarpaulin --verbose --all-features --out xml

      - name: Codecov
        uses: codecov/codecov-action@v5.4.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}